language: python
python: "2.7"
env:
  - PLONE_VERSION=4
  - PLONE_VERSION=5
install:
  - mkdir -p buildout-cache/downloads
  - python bootstrap.py -c travis-$PLONE_VERSION.x.cfg -v 1.6.3
  - bin/buildout -c travis-$PLONE_VERSION.x.cfg
script:
  - bin/test
